Repository Unbancho/Jeffistance, pull requests merged in 2020-05, with the labels that each got.

#29 New ready lobby
  Jeffistance.Client/Models/AppState.cs
  Jeffistance.Client/Services/MessageProcessing.cs
  Jeffistance.Client/ViewModels/HostMenuViewModel.cs
  Jeffistance.Client/ViewModels/JoinMenuViewModel.cs
  Jeffistance.Client/ViewModels/LobbyViewModel.cs
  Jeffistance.Client/Views/LobbyView.xaml
  Jeffistance.Common/Models/User.cs
  Jeffistance.Common/Services/MessageProcessing.cs
  Jeffistance.Server/Models/Server.cs
  Jeffistance.Server/Services/MessageProcessing.cs
Labels: design, enhancement

#32 Add a dependency manager
  Jeffistance.Common/Services/IoC/DependencyCollection.cs
  Jeffistance.Common/Services/IoC/IoCManager.cs
  Jeffistance.Common/Services/IoC/UnregisteredTypeException.cs
Labels: enhancement

#33 Game view screen
  Jeffistance.Client/Assets/Sharkbisu.png
  Jeffistance.Client/Assets/Skullbisu.png
  Jeffistance.Client/Assets/Spy.png
  Jeffistance.Client/Assets/Vorebisu.png
  Jeffistance.Client/Panels/CircularPanel.cs
  Jeffistance.Client/Services/MessageProcessing.cs
  Jeffistance.Client/ViewModels/GameScreenViewModel.cs
  Jeffistance.Client/ViewModels/LobbyViewModel.cs
  Jeffistance.Client/ViewModels/PlayerAreaViewModel.cs
  Jeffistance.Client/Views/ChatView.xaml
  Jeffistance.Client/Views/GameScreenView.xaml
  Jeffistance.Client/Views/GameScreenView.xaml.cs
  Jeffistance.Client/Views/PlayerAreaView.xaml
  Jeffistance.Client/Views/PlayerAreaView.xaml.cs
  Jeffistance.Client/Views/PlayerAvatarView.xaml
  Jeffistance.Client/Views/PlayerAvatarView.xaml.cs
  Jeffistance.Client/Views/ScoreNodeView.xaml
  Jeffistance.Client/Views/ScoreNodeView.xaml.cs
  Jeffistance.Common/Services/MessageProcessing.cs
  Jeffistance.Server/Services/MessageProcessing.cs
Labels: design, enhancement

#34 Message factory
  Jeffistance.Client/App.xaml.cs
  Jeffistance.Client/ViewModels/ChatMessageViewModel.cs
  Jeffistance.Client/ViewModels/ChatViewModel.cs
  Jeffistance.Client/ViewModels/LobbyViewModel.cs
  Jeffistance.Common/Models/User.cs
  Jeffistance.Common/Services/ClientMessageFactory.cs
  Jeffistance.Common/Services/IoC/DependencyCollection.cs
  Jeffistance.Common/Services/IoC/IoCManager.cs
  Jeffistance.Server/Models/Server.cs
  Jeffistance.Server/Services/ServerMessageFactory.cs
  Jeffistance.Test/Dummies/DummyMessageFactory.cs
  Jeffistance.Test/IoCTest.cs
Labels: refactoring
