Repository Unbancho/Jeffistance, pull requests merged in 2020-06, with the labels that each got.

#36 Quality of life task stuff
  .vscode/launch.json
  .vscode/tasks.json
Labels: QoL

#37 Add logging
  .gitignore
  Jeffistance.Client/App.xaml.cs
  Jeffistance.Common/Jeffistance.Common.csproj
  Jeffistance.Common/Services/IoC/DependencyCollection.cs
  Jeffistance.Common/Services/IoC/IoCManager.cs
  Jeffistance.Server/Models/Server.cs
Labels: QoL, enhancement

#38 Log stuff
  Jeffistance.Client/App.xaml.cs
  Jeffistance.Client/Services/MessageProcessing.cs
  Jeffistance.Client/ViewModels/HostMenuViewModel.cs
  Jeffistance.Client/ViewModels/JoinMenuViewModel.cs
  Jeffistance.Client/app.config
  Jeffistance.Common/Jeffistance.Common.csproj
  Jeffistance.Common/Services/MessageProcessing.cs
  Jeffistance.Common/Utils/ExtensionMethods.cs
  Jeffistance.Server/Models/Server.cs
  Jeffistance.Server/Services/MessageProcessing.cs
  Jeffistance.Server/app.config
Labels: QoL, enhancement

#39 Better visuals
  Jeffistance.Client/Assets/RoundStateNormal.png
  Jeffistance.Client/Assets/RoundStateResistenceVictory.png
  Jeffistance.Client/Assets/RoundStateSpyVictory.png
  Jeffistance.Client/Assets/Selected Spy.png
  Jeffistance.Client/Assets/Sharkbisu.png
  Jeffistance.Client/Assets/Skullbisu.png
  Jeffistance.Client/Assets/Vorebisu.png
  Jeffistance.Client/ViewModels/GameScreenViewModel.cs
  Jeffistance.Client/Views/ChatMessageView.xaml
  Jeffistance.Client/Views/GameScreenView.xaml
  Jeffistance.Client/Views/ScoreNodeView.xaml
  Jeffistance.Client/Views/ScoreNodeView.xaml.cs
Labels: design, enhancement

#42 Project release update
  Jeffistance.Client/Jeffistance.Client.csproj
  Jeffistance.Common/Services/MessageProcessing.cs
Labels: enhancement

#46 Chat manager
  Jeffistance.Client/App.xaml.cs
  Jeffistance.Client/Services/ClientChatManager.cs
  Jeffistance.Client/Services/MessageProcessing.cs
  Jeffistance.Client/ViewModels/ChatViewModel.cs
  Jeffistance.Client/ViewModels/HostMenuViewModel.cs
  Jeffistance.Client/ViewModels/JoinMenuViewModel.cs
  Jeffistance.Client/ViewModels/LobbyViewModel.cs
  Jeffistance.Common/Models/User.cs
  Jeffistance.Common/Services/MessageProcessing.cs
  Jeffistance.Server/Models/Server.cs
  Jeffistance.Server/Models/ServerLobby.cs
  Jeffistance.Server/Services/MessageProcessing.cs
  Jeffistance.Server/Services/ServerChatManager.cs
  Jeffistance.Server/Services/ServerMessageFactory.cs
Labels: enhancement, networking, refactoring
